export const notificationItems = [
  {
    id: "n1",
    type: "email",
    title: "새 이메일이 도착했습니다",
    content: "박민수 · 엔터프라이즈 플랜 가격 문의",
    time: "5분 전",
    actionLabel: "확인하기",
    actionPath: "/app/inbox",
    read: false,
    tone: "teal",
  },
  {
    id: "n2",
    type: "draft",
    title: "검토 대기 중인 초안이 있습니다",
    content: "3개의 초안이 검토를 기다리고 있습니다",
    time: "10분 전",
    actionLabel: "바로 확인",
    actionPath: "/app/inbox",
    read: false,
    tone: "amber",
  },
  {
    id: "n3",
    type: "error",
    title: "이메일 계정 연결이 끊겼습니다",
    content: "user@gmail.com 재연결이 필요합니다",
    time: "1시간 전",
    actionLabel: "재연결",
    actionPath: "/app/settings",
    read: false,
    tone: "red",
  },
  {
    id: "n4",
    type: "calendar",
    title: "등록 대기 중인 일정이 있습니다",
    content: "테크솔루션 엔터프라이즈 플랜 상담 · 3월 4일 14:00",
    time: "20분 전",
    actionLabel: "일정 확인",
    actionPath: "/app/calendar",
    read: true,
    tone: "teal",
  },
];
