export const calendarEvents = [
  {
    id: "c1",
    title: "테크솔루션 엔터프라이즈 플랜 상담",
    dateLabel: "3월 4일 (수)",
    timeLabel: "14:00 - 15:00",
    source: "이메일 감지",
    type: "video",
    sender: "박민수",
    company: "(주)테크솔루션",
    approved: true,
  },
  {
    id: "c2",
    title: "그린에너지 파트너십 미팅",
    dateLabel: "3월 5일 (목)",
    timeLabel: "10:00 - 11:30",
    source: "직접 등록",
    type: "meeting",
    sender: "최영호",
    company: "그린에너지",
    approved: false,
  },
  {
    id: "c3",
    title: "디자인랩 계약 갱신 미팅",
    dateLabel: "3월 7일 (토)",
    timeLabel: "15:00 - 16:00",
    source: "이메일 감지",
    type: "video",
    sender: "정하나",
    company: "디자인랩",
    approved: true,
  },
];
