export const userIaSections = [
  {
    group: "Public Entry",
    items: [
      {
        path: "/",
        title: "로그인 / 회원가입",
        note: "서비스 계정 인증 시작 화면. 온보딩 진입 전 로그인과 가입을 처리한다.",
      },
      {
        path: "/onboarding",
        title: "온보딩",
        note: "Gmail 연동, 회사 프로필, 자료 업로드, 카테고리, 템플릿 생성까지 한 흐름으로 진행한다.",
      },
    ],
  },
  {
    group: "Workspace",
    items: [
      {
        path: "/app",
        title: "대시보드",
        note: "요약 메트릭, 최근 메일, 다가오는 일정 확인.",
      },
      {
        path: "/app/inbox",
        title: "수신함",
        note: "메일 목록, 본문 상세, 답변 초안 검토와 발송.",
      },
      {
        path: "/app/calendar",
        title: "캘린더",
        note: "일정 월간 보기, 이메일 기반 일정 확인, 일정 생성/수정.",
      },
      {
        path: "/app/templates",
        title: "템플릿 라이브러리",
        note: "카테고리별 템플릿 검색, 생성, 수정, 삭제.",
      },
      {
        path: "/app/profile",
        title: "비즈니스 프로필",
        note: "회사 정보, 자료 업로드, FAQ, 템플릿 재생성.",
      },
      {
        path: "/app/automation",
        title: "자동화 설정",
        note: "카테고리 규칙, 자동 발송, 캘린더 연동 설정.",
      },
      {
        path: "/app/settings",
        title: "설정",
        note: "계정, 알림, 이메일 연동, 관리자 문의 탭.",
      },
    ],
  },
];

export const adminIaSections = [
  {
    group: "Admin Navigation",
    items: [
      {
        path: "/",
        title: "운영 대시보드",
        note: "처리량, 도메인 비율, 부서 사용량, 메시지 파이프라인 모니터링.",
      },
      {
        path: "/members",
        title: "회원 관리",
        note: "회원 검색, 부서 정책, 업종 / 카테고리 운영 범위 확인.",
      },
      {
        path: "/templates",
        title: "업종 / 카테고리 관리",
        note: "사용자 앱과 동일한 업종 / 비즈니스 유형, 카테고리 기준을 관리.",
      },
      {
        path: "/inquiries",
        title: "사용자 문의 대응",
        note: "문의 리스트, 상세 정보, 답변 이력 확인.",
      },
    ],
  },
];

export const userFeatureMap = [
  {
    screen: "로그인 / 회원가입",
    route: "/",
    features: [
      "로그인과 회원가입 모드 전환",
      "서비스 소개 레이아웃 공통 사용",
      "유효성 오류와 로그인 처리 실패 상태 노출",
    ],
    scenarios: [
      "auth-login-validation",
      "auth-signup-validation",
      "auth-login-service-error",
    ],
  },
  {
    screen: "온보딩",
    route: "/onboarding",
    features: [
      "Gmail 연동",
      "회사 프로필 / 자료 업로드 / FAQ 입력",
      "카테고리 설정과 템플릿 생성 진행",
    ],
    scenarios: [
      "onboarding-google-oauth-error",
      "onboarding-upload-error",
      "onboarding-template-generation-error",
    ],
  },
  {
    screen: "대시보드",
    route: "/app",
    features: [
      "핵심 메트릭 카드",
      "최근 메일 / 일정 요약 패널",
      "세션 만료 / 서비스 장애 / 예기치 않은 오류 전면 상태",
    ],
    scenarios: [
      "dashboard-load-error",
      "dashboard-calendar-panel-error",
      "dashboard-email-panel-error",
      "global-session-expired",
      "global-service-unavailable",
      "global-unexpected-error",
    ],
  },
  {
    screen: "수신함",
    route: "/app/inbox",
    features: [
      "메일 목록과 상태 필터",
      "본문 상세와 답변 초안 패널",
      "빈 상태, 목록 오류, 상세 오류, 발송 실패, 일정 감지 실패",
    ],
    scenarios: [
      "inbox-empty",
      "inbox-list-error",
      "inbox-thread-error",
      "inbox-draft-send-error",
      "inbox-schedule-detect-error",
    ],
  },
  {
    screen: "캘린더",
    route: "/app/calendar",
    features: [
      "월간 캘린더와 일정 상세",
      "일정 생성/수정 다이얼로그",
      "빈 상태, 동기화 오류, 저장 실패",
    ],
    scenarios: [
      "calendar-load-error",
      "calendar-empty",
      "calendar-sync-error",
      "calendar-create-error",
    ],
  },
  {
    screen: "템플릿 / 프로필 / 자동화",
    route: "/app/templates, /app/profile, /app/automation",
    features: [
      "템플릿 CRUD와 빈 상태",
      "프로필 저장, 자료 업로드, FAQ, 템플릿 재생성",
      "카테고리 규칙과 캘린더 연동 상태",
    ],
    scenarios: [
      "templates-load-error",
      "templates-empty",
      "templates-save-error",
      "profile-save-error",
      "profile-upload-error",
      "profile-faq-save-error",
      "profile-regenerate-error",
      "automation-load-error",
      "automation-rule-save-error",
      "automation-calendar-disconnected",
    ],
  },
  {
    screen: "설정",
    route: "/app/settings",
    features: [
      "계정 저장 / 비밀번호 변경",
      "이메일 연동 OAuth 확인",
      "관리자 문의 등록",
    ],
    scenarios: [
      "settings-account-save-error",
      "settings-password-validation-error",
      "settings-email-oauth-error",
      "settings-support-submit-error",
    ],
  },
  {
    screen: "공통 오류",
    route: "/missing-page",
    features: [
      "404 페이지",
      "대시보드 / 로그인으로 복귀 링크",
    ],
    scenarios: ["global-not-found"],
  },
];

export const adminFeatureMap = [
  {
    screen: "운영 대시보드",
    route: "/",
    features: [
      "운영 메트릭 카드",
      "도메인 비율, 처리량, 메시지 큐 모니터링",
      "권한 없음 / 전면 오류 / 큐 패널 오류 상태",
    ],
    scenarios: [
      "admin-dashboard-load-error",
      "admin-dashboard-queue-error",
      "admin-permission-denied",
      "admin-unexpected-error",
    ],
  },
  {
    screen: "회원 관리",
    route: "/members",
    features: [
      "회원 목록, 검색, 부서 필터",
      "부서 정책과 업종 / 카테고리 운영 범위 표시",
      "목록 로드 실패와 빈 결과 상태",
    ],
    scenarios: [
      "admin-members-load-error",
      "admin-members-empty",
    ],
  },
  {
    screen: "업종 / 카테고리 관리",
    route: "/templates",
    features: [
      "App와 동일한 업종 / 비즈니스 유형 목록",
      "업종별 카테고리 카탈로그와 색상 기준",
      "LLM 템플릿 생성 기준과 운영 원칙 확인",
    ],
    scenarios: [
      "admin-templates-load-error",
      "admin-templates-approval-error",
    ],
  },
  {
    screen: "사용자 문의 대응",
    route: "/inquiries",
    features: [
      "문의 리스트와 상세 패널",
      "답변 이력 확인",
      "전면 로드 실패와 빈 상태",
    ],
    scenarios: [
      "admin-inquiries-load-error",
      "admin-inquiries-empty",
      "admin-not-found",
    ],
  },
];

const desktopViewport = {
  width: 1440,
  height: 1024,
};

export const userNormalCaptures = [
  {
    captureId: "auth-login-normal",
    route: "/",
    screenTitle: "로그인 기본 화면",
    stateType: "normal",
    outputFile: "screenshots/normal/user/auth-login.png",
    viewport: desktopViewport,
    description: "비로그인 상태의 로그인 기본 화면",
  },
  {
    captureId: "auth-signup-normal",
    route: "/?scenario=auth-signup-normal",
    screenTitle: "회원가입 기본 화면",
    stateType: "normal",
    outputFile: "screenshots/normal/user/auth-signup.png",
    viewport: desktopViewport,
    description: "회원가입 입력 폼이 보이는 인증 기본 화면",
  },
  {
    captureId: "onboarding-normal",
    route: "/onboarding",
    screenTitle: "온보딩 기본 화면",
    stateType: "normal",
    outputFile: "screenshots/normal/user/onboarding.png",
    viewport: desktopViewport,
    description: "Gmail 연동과 회사 정보 입력을 시작하는 온보딩 기본 화면",
  },
  {
    captureId: "onboarding-profile-normal",
    route: "/onboarding?scenario=onboarding-profile-normal",
    screenTitle: "온보딩 회사 프로필 단계",
    stateType: "normal",
    outputFile: "screenshots/normal/user/onboarding-profile.png",
    viewport: desktopViewport,
    description: "온보딩 비즈니스 설정 첫 단계가 열린 화면",
  },
  {
    captureId: "onboarding-knowledge-normal",
    route: "/onboarding?scenario=onboarding-knowledge-normal",
    screenTitle: "온보딩 자료 업로드 단계",
    stateType: "normal",
    outputFile: "screenshots/normal/user/onboarding-knowledge.png",
    viewport: desktopViewport,
    description: "비즈니스 자료 업로드와 FAQ 입력 단계가 열린 화면",
  },
  {
    captureId: "onboarding-categories-normal",
    route: "/onboarding?scenario=onboarding-categories-normal",
    screenTitle: "온보딩 카테고리 설정 단계",
    stateType: "normal",
    outputFile: "screenshots/normal/user/onboarding-categories.png",
    viewport: desktopViewport,
    description: "추천 카테고리와 카테고리 미리보기가 보이는 단계",
  },
  {
    captureId: "onboarding-generating-normal",
    route: "/onboarding?scenario=onboarding-generating-normal",
    screenTitle: "온보딩 템플릿 생성 진행 상태",
    stateType: "normal",
    outputFile: "screenshots/normal/user/onboarding-generating.png",
    viewport: desktopViewport,
    description: "템플릿 자동 생성 진행 중인 상태 화면",
  },
  {
    captureId: "onboarding-complete-normal",
    route: "/onboarding?scenario=onboarding-complete-normal",
    screenTitle: "온보딩 완료 화면",
    stateType: "normal",
    outputFile: "screenshots/normal/user/onboarding-complete.png",
    viewport: desktopViewport,
    description: "온보딩 완료 후 시작 안내가 보이는 화면",
  },
  {
    captureId: "dashboard-normal",
    route: "/app",
    screenTitle: "대시보드 기본 화면",
    stateType: "normal",
    outputFile: "screenshots/normal/user/dashboard.png",
    viewport: desktopViewport,
    description: "메트릭, 최근 메일, 일정 요약이 보이는 대시보드 기본 화면",
  },
  {
    captureId: "inbox-normal",
    route: "/app/inbox",
    screenTitle: "수신함 기본 화면",
    stateType: "normal",
    outputFile: "screenshots/normal/user/inbox.png",
    viewport: desktopViewport,
    description: "메일 목록과 상세, 초안 패널이 함께 보이는 수신함 기본 화면",
  },
  {
    captureId: "calendar-normal",
    route: "/app/calendar",
    screenTitle: "캘린더 기본 화면",
    stateType: "normal",
    outputFile: "screenshots/normal/user/calendar.png",
    viewport: desktopViewport,
    description: "월간 캘린더와 일정 상세가 보이는 기본 화면",
  },
  {
    captureId: "calendar-create-normal",
    route: "/app/calendar?scenario=calendar-create-normal",
    screenTitle: "캘린더 일정 추가 다이얼로그",
    stateType: "normal",
    outputFile: "screenshots/normal/user/calendar-create.png",
    viewport: desktopViewport,
    description: "일정 추가 다이얼로그가 열린 정상 상태",
  },
  {
    captureId: "calendar-edit-normal",
    route: "/app/calendar?scenario=calendar-edit-normal",
    screenTitle: "캘린더 일정 수정 다이얼로그",
    stateType: "normal",
    outputFile: "screenshots/normal/user/calendar-edit.png",
    viewport: desktopViewport,
    description: "기존 일정 수정 다이얼로그가 열린 정상 상태",
  },
  {
    captureId: "templates-normal",
    route: "/app/templates",
    screenTitle: "템플릿 라이브러리 기본 화면",
    stateType: "normal",
    outputFile: "screenshots/normal/user/templates.png",
    viewport: desktopViewport,
    description: "템플릿 검색, 목록, 편집 진입이 가능한 기본 화면",
  },
  {
    captureId: "templates-preview-normal",
    route: "/app/templates?scenario=templates-preview-normal",
    screenTitle: "템플릿 미리보기 다이얼로그",
    stateType: "normal",
    outputFile: "screenshots/normal/user/templates-preview.png",
    viewport: desktopViewport,
    description: "템플릿 본문 미리보기 다이얼로그가 열린 정상 상태",
  },
  {
    captureId: "templates-edit-normal",
    route: "/app/templates?scenario=templates-edit-normal",
    screenTitle: "템플릿 편집 다이얼로그",
    stateType: "normal",
    outputFile: "screenshots/normal/user/templates-edit.png",
    viewport: desktopViewport,
    description: "템플릿 수정 다이얼로그가 열린 정상 상태",
  },
  {
    captureId: "profile-normal",
    route: "/app/profile",
    screenTitle: "비즈니스 프로필 기본 화면",
    stateType: "normal",
    outputFile: "screenshots/normal/user/profile.png",
    viewport: desktopViewport,
    description: "회사 정보와 자료 업로드, FAQ 설정이 보이는 기본 화면",
  },
  {
    captureId: "profile-faq-dialog-normal",
    route: "/app/profile?scenario=profile-faq-dialog-normal",
    screenTitle: "비즈니스 프로필 FAQ 다이얼로그",
    stateType: "normal",
    outputFile: "screenshots/normal/user/profile-faq-dialog.png",
    viewport: desktopViewport,
    description: "FAQ 항목 추가 다이얼로그가 열린 정상 상태",
  },
  {
    captureId: "profile-regenerate-select-normal",
    route: "/app/profile?scenario=profile-regenerate-select-normal",
    screenTitle: "비즈니스 프로필 재생성 선택 다이얼로그",
    stateType: "normal",
    outputFile: "screenshots/normal/user/profile-regenerate-select.png",
    viewport: desktopViewport,
    description: "재생성할 템플릿을 선택하는 다이얼로그가 열린 정상 상태",
  },
  {
    captureId: "automation-normal",
    route: "/app/automation",
    screenTitle: "자동화 설정 기본 화면",
    stateType: "normal",
    outputFile: "screenshots/normal/user/automation.png",
    viewport: desktopViewport,
    description: "카테고리 규칙과 캘린더 연동 상태를 확인하는 기본 화면",
  },
  {
    captureId: "automation-rule-dialog-normal",
    route: "/app/automation?scenario=automation-rule-dialog-normal",
    screenTitle: "자동화 설정 규칙 추가 다이얼로그",
    stateType: "normal",
    outputFile: "screenshots/normal/user/automation-rule-dialog.png",
    viewport: desktopViewport,
    description: "카테고리 규칙 추가 다이얼로그가 열린 정상 상태",
  },
  {
    captureId: "automation-calendar-category-normal",
    route: "/app/automation?scenario=automation-calendar-category-normal",
    screenTitle: "자동화 설정 캘린더 카테고리 다이얼로그",
    stateType: "normal",
    outputFile: "screenshots/normal/user/automation-calendar-category.png",
    viewport: desktopViewport,
    description: "캘린더 자동 등록 카테고리 선택 다이얼로그가 열린 정상 상태",
  },
  {
    captureId: "settings-account-normal",
    route: "/app/settings?tab=account",
    screenTitle: "설정 계정 탭 기본 화면",
    stateType: "normal",
    outputFile: "screenshots/normal/user/settings-account.png",
    viewport: desktopViewport,
    description: "계정 정보와 비밀번호 변경이 보이는 설정 기본 화면",
  },
  {
    captureId: "settings-notifications-normal",
    route: "/app/settings?tab=notifications",
    screenTitle: "설정 알림 탭 기본 화면",
    stateType: "normal",
    outputFile: "screenshots/normal/user/settings-notifications.png",
    viewport: desktopViewport,
    description: "알림 설정 토글이 보이는 설정 기본 화면",
  },
  {
    captureId: "settings-display-normal",
    route: "/app/settings?tab=display",
    screenTitle: "설정 화면 탭 기본 화면",
    stateType: "normal",
    outputFile: "screenshots/normal/user/settings-display.png",
    viewport: desktopViewport,
    description: "테마와 표시 옵션을 조정하는 화면 설정 탭 기본 화면",
  },
  {
    captureId: "settings-email-normal",
    route: "/app/settings?tab=email",
    screenTitle: "설정 이메일 연동 탭 기본 화면",
    stateType: "normal",
    outputFile: "screenshots/normal/user/settings-email.png",
    viewport: desktopViewport,
    description: "연결된 Gmail 계정 목록과 계정 추가 버튼이 보이는 기본 화면",
  },
  {
    captureId: "settings-email-oauth-verify-normal",
    route: "/app/settings?tab=email&scenario=settings-email-oauth-verify-normal",
    screenTitle: "설정 이메일 연동 OAuth 확인 다이얼로그",
    stateType: "normal",
    outputFile: "screenshots/normal/user/settings-email-oauth-verify.png",
    viewport: desktopViewport,
    description: "Google 인증 확인 다이얼로그가 열린 정상 상태",
  },
  {
    captureId: "settings-support-normal",
    route: "/app/settings?tab=support",
    screenTitle: "설정 관리자 문의 탭 기본 화면",
    stateType: "normal",
    outputFile: "screenshots/normal/user/settings-support.png",
    viewport: desktopViewport,
    description: "관리자 문의 작성 폼이 보이는 설정 기본 화면",
  },
  {
    captureId: "settings-support-dialog-normal",
    route: "/app/settings?tab=support&scenario=settings-support-dialog-normal",
    screenTitle: "설정 관리자 문의 작성 다이얼로그",
    stateType: "normal",
    outputFile: "screenshots/normal/user/settings-support-dialog.png",
    viewport: desktopViewport,
    description: "관리자 문의 작성 다이얼로그가 열린 정상 상태",
  },
];

export const adminNormalCaptures = [
  {
    captureId: "admin-dashboard-normal",
    route: "/",
    screenTitle: "관리자 대시보드 기본 화면",
    stateType: "normal",
    outputFile: "screenshots/normal/admin/dashboard.png",
    viewport: desktopViewport,
    description: "운영 메트릭과 큐 현황이 보이는 관리자 기본 화면",
  },
  {
    captureId: "admin-members-normal",
    route: "/members",
    screenTitle: "회원 관리 기본 화면",
    stateType: "normal",
    outputFile: "screenshots/normal/admin/members.png",
    viewport: desktopViewport,
    description: "회원 목록과 부서 정책이 보이는 관리자 기본 화면",
  },
  {
    captureId: "admin-templates-normal",
    route: "/templates",
    screenTitle: "업종 / 카테고리 관리 기본 화면",
    stateType: "normal",
    outputFile: "screenshots/normal/admin/templates.png",
    viewport: desktopViewport,
    description: "업종 / 비즈니스 유형과 카테고리 기준을 관리하는 기본 화면",
  },
  {
    captureId: "admin-inquiries-normal",
    route: "/inquiries",
    screenTitle: "문의 대응 기본 화면",
    stateType: "normal",
    outputFile: "screenshots/normal/admin/inquiries.png",
    viewport: desktopViewport,
    description: "문의 목록과 상세 패널이 보이는 관리자 기본 화면",
  },
];
