export const userIaSections = [
  {
    group: "Public Entry",
    items: [
      {
        path: "/",
        title: "로그인 / 회원가입",
        note: "서비스 계정 인증 시작 화면. 온보딩 진입 전 로그인과 가입을 처리한다.",
      },
      {
        path: "/onboarding",
        title: "온보딩",
        note: "Gmail 연동, 회사 프로필, 자료 업로드, 카테고리, 템플릿 생성까지 한 흐름으로 진행한다.",
      },
    ],
  },
  {
    group: "Workspace",
    items: [
      {
        path: "/app",
        title: "대시보드",
        note: "요약 메트릭, 최근 메일, 다가오는 일정 확인.",
      },
      {
        path: "/app/inbox",
        title: "수신함",
        note: "메일 목록, 본문 상세, 답변 초안 검토와 발송.",
      },
      {
        path: "/app/calendar",
        title: "캘린더",
        note: "일정 월간 보기, 이메일 기반 일정 확인, 일정 생성/수정.",
      },
      {
        path: "/app/templates",
        title: "템플릿 라이브러리",
        note: "카테고리별 템플릿 검색, 생성, 수정, 삭제.",
      },
      {
        path: "/app/profile",
        title: "비즈니스 프로필",
        note: "회사 정보, 자료 업로드, FAQ, 템플릿 재생성.",
      },
      {
        path: "/app/automation",
        title: "자동화 설정",
        note: "카테고리 규칙, 자동 발송, 캘린더 연동 설정.",
      },
      {
        path: "/app/settings",
        title: "설정",
        note: "계정, 알림, 이메일 연동, 관리자 문의 탭.",
      },
    ],
  },
];

export const adminIaSections = [
  {
    group: "Admin Navigation",
    items: [
      {
        path: "/admin",
        title: "운영 대시보드",
        note: "가입 사용자, 연동 완료 사용자, AI 분석/초안 생성, 문의 접수와 처리 추이를 요약.",
      },
      {
        path: "/admin/users",
        title: "사용자 관리",
        note: "이름/이메일/업종 검색, 계정 활성/비활성, Google 연동 상태와 강제 해제.",
      },
      {
        path: "/admin/template-automation",
        title: "템플릿 / 자동화 관리",
        note: "생성 템플릿 사용 현황, 카테고리 통계, 자동화 규칙 생성/수정/삭제.",
      },
      {
        path: "/admin/inquiries",
        title: "사용자 문의 대응",
        note: "문의 리스트, 상세 정보, 답변 작성과 답변 이력 확인.",
      },
      {
        path: "/admin/monitoring",
        title: "시스템 운영 모니터링",
        note: "실패/대기 작업 강제 삭제.",
      },
    ],
  },
];

export const userFeatureMap = [
  {
    screen: "로그인 / 회원가입",
    route: "/",
    features: [
      "로그인과 회원가입 모드 전환",
      "이름과 이메일 기반 비밀번호 재설정",
      "서비스 소개 레이아웃 공통 사용",
      "유효성 오류와 로그인 처리 실패 상태 노출",
    ],
    scenarios: [
      "auth-reset-normal",
      "auth-reset-complete-normal",
      "auth-login-validation",
      "auth-signup-validation",
      "auth-login-service-error",
    ],
  },
  {
    screen: "온보딩",
    route: "/onboarding",
    features: [
      "Gmail 연동",
      "회사 프로필 / 자료 업로드 / FAQ 입력",
      "카테고리 드롭다운, 직접 추가, 템플릿 생성 진행",
    ],
    scenarios: [
      "onboarding-categories-dropdown-normal",
      "onboarding-categories-custom-normal",
      "onboarding-google-oauth-error",
      "onboarding-upload-error",
      "onboarding-template-generation-error",
    ],
  },
  {
    screen: "대시보드",
    route: "/app",
    features: [
      "핵심 메트릭 카드",
      "최근 메일 / 일정 요약 패널",
      "세션 만료 / 서비스 장애 / 예기치 않은 오류 전면 상태",
    ],
    scenarios: [
      "dashboard-load-error",
      "dashboard-calendar-panel-error",
      "dashboard-email-panel-error",
      "global-session-expired",
      "global-service-unavailable",
      "global-unexpected-error",
    ],
  },
  {
    screen: "수신함",
    route: "/app/inbox",
    features: [
      "메일 목록과 상태 필터",
      "본문 상세와 답변 초안 패널",
      "빈 상태, 목록 오류, 상세 오류, 발송 실패, 일정 감지 실패",
    ],
    scenarios: [
      "inbox-empty",
      "inbox-list-error",
      "inbox-thread-error",
      "inbox-draft-send-error",
      "inbox-schedule-detect-error",
    ],
  },
  {
    screen: "캘린더",
    route: "/app/calendar",
    features: [
      "월간 캘린더와 일정 상세",
      "일정 생성/수정 다이얼로그",
      "빈 상태, 동기화 오류, 저장 실패",
    ],
    scenarios: [
      "calendar-load-error",
      "calendar-empty",
      "calendar-sync-error",
      "calendar-create-error",
    ],
  },
  {
    screen: "템플릿 / 프로필 / 자동화",
    route: "/app/templates, /app/profile, /app/automation",
    features: [
      "템플릿 CRUD와 빈 상태",
      "프로필 저장, 자료 업로드, FAQ, 템플릿 재생성",
      "카테고리 규칙과 캘린더 연동 상태",
    ],
    scenarios: [
      "templates-load-error",
      "templates-empty",
      "templates-save-error",
      "profile-save-error",
      "profile-upload-error",
      "profile-faq-save-error",
      "profile-regenerate-error",
      "automation-load-error",
      "automation-rule-save-error",
      "automation-calendar-disconnected",
    ],
  },
  {
    screen: "설정",
    route: "/app/settings",
    features: [
      "계정 저장 / 비밀번호 변경",
      "이메일 연동 OAuth 확인",
      "관리자 문의 등록",
    ],
    scenarios: [
      "settings-account-save-error",
      "settings-password-validation-error",
      "settings-email-oauth-error",
      "settings-support-submit-error",
    ],
  },
  {
    screen: "공통 오류",
    route: "/missing-page",
    features: [
      "404 페이지",
      "대시보드 / 로그인으로 복귀 링크",
    ],
    scenarios: ["global-not-found"],
  },
];

export const adminFeatureMap = [
  {
    screen: "운영 대시보드",
    route: "/admin",
    features: [
      "가입 사용자, 연동 완료 사용자, AI 분석/초안 생성, 문의 접수 KPI",
      "기간별 메일 처리량, 도메인 분포, 최근 7일 처리 추이",
      "권한 없음 / 전면 오류 / 추이 패널 오류 상태",
    ],
    scenarios: [
      "admin-dashboard-load-error",
      "admin-dashboard-trend-error",
      "admin-permission-denied",
      "admin-unexpected-error",
    ],
  },
  {
    screen: "사용자 관리",
    route: "/admin/users",
    features: [
      "사용자 목록, 이름/이메일/업종 검색",
      "계정 활성/비활성, Google 연동 강제 해제",
      "목록 로드 실패, 빈 결과, 운영 액션 실패 상태",
    ],
    scenarios: [
      "admin-users-load-error",
      "admin-users-empty",
      "admin-users-action-error",
    ],
  },
  {
    screen: "템플릿 / 자동화 관리",
    route: "/admin/template-automation",
    features: [
      "생성 템플릿 사용 현황과 카테고리 통계",
      "자동화 규칙 생성/수정/삭제",
      "전면 로드 실패, 템플릿 빈 상태, 규칙 빈 상태, 규칙 저장 실패",
    ],
    scenarios: [
      "admin-template-automation-load-error",
      "admin-template-automation-templates-empty",
      "admin-template-automation-rules-empty",
      "admin-template-automation-rule-save-error",
    ],
  },
  {
    screen: "사용자 문의 대응",
    route: "/admin/inquiries",
    features: [
      "문의 리스트와 상세 패널",
      "답변 작성과 답변 이력 확인",
      "전면 로드 실패, 빈 상태, 답변 저장 실패",
    ],
    scenarios: [
      "admin-inquiries-load-error",
      "admin-inquiries-empty",
      "admin-inquiries-reply-error",
      "admin-not-found",
    ],
  },
  {
    screen: "시스템 운영 모니터링",
    route: "/admin/monitoring",
    features: [
      "실패/대기 작업 목록 확인",
      "작업 강제 삭제",
      "로드 실패, 빈 상태, 삭제 실패 상태",
    ],
    scenarios: [
      "admin-monitoring-load-error",
      "admin-monitoring-empty",
      "admin-monitoring-delete-error",
    ],
  },
];

const desktopViewport = {
  width: 1440,
  height: 1024,
};

export const userNormalCaptures = [
  {
    captureId: "auth-login-normal",
    route: "/",
    screenTitle: "로그인 기본 화면",
    stateType: "normal",
    outputFile: "screenshots/normal/user/auth-login.png",
    viewport: desktopViewport,
    description: "비로그인 상태의 로그인 기본 화면",
  },
  {
    captureId: "auth-signup-normal",
    route: "/?scenario=auth-signup-normal",
    screenTitle: "회원가입 기본 화면",
    stateType: "normal",
    outputFile: "screenshots/normal/user/auth-signup.png",
    viewport: desktopViewport,
    description: "회원가입 입력 폼이 보이는 인증 기본 화면",
  },
  {
    captureId: "auth-reset-normal",
    route: "/?scenario=auth-reset-normal",
    screenTitle: "비밀번호 찾기 기본 화면",
    stateType: "normal",
    outputFile: "screenshots/normal/user/auth-reset.png",
    viewport: desktopViewport,
    description: "이름과 이메일을 확인한 뒤 새 비밀번호를 직접 설정하는 화면",
  },
  {
    captureId: "auth-reset-complete-normal",
    route: "/?scenario=auth-reset-complete-normal",
    screenTitle: "비밀번호 재설정 완료 화면",
    stateType: "normal",
    outputFile: "screenshots/normal/user/auth-reset-complete.png",
    viewport: desktopViewport,
    description: "새 비밀번호 설정이 완료되어 로그인 복귀를 안내하는 화면",
  },
  {
    captureId: "onboarding-normal",
    route: "/onboarding",
    screenTitle: "온보딩 기본 화면",
    stateType: "normal",
    outputFile: "screenshots/normal/user/onboarding.png",
    viewport: desktopViewport,
    description: "Gmail 연동과 회사 정보 입력을 시작하는 온보딩 기본 화면",
  },
  {
    captureId: "onboarding-profile-normal",
    route: "/onboarding?scenario=onboarding-profile-normal",
    screenTitle: "온보딩 회사 프로필 단계",
    stateType: "normal",
    outputFile: "screenshots/normal/user/onboarding-profile.png",
    viewport: desktopViewport,
    description: "온보딩 비즈니스 설정 첫 단계가 열린 화면",
  },
  {
    captureId: "onboarding-knowledge-normal",
    route: "/onboarding?scenario=onboarding-knowledge-normal",
    screenTitle: "온보딩 자료 업로드 단계",
    stateType: "normal",
    outputFile: "screenshots/normal/user/onboarding-knowledge.png",
    viewport: desktopViewport,
    description: "비즈니스 자료 업로드와 FAQ 입력 단계가 열린 화면",
  },
  {
    captureId: "onboarding-categories-normal",
    route: "/onboarding?scenario=onboarding-categories-normal",
    screenTitle: "온보딩 카테고리 설정 단계",
    stateType: "normal",
    outputFile: "screenshots/normal/user/onboarding-categories.png",
    viewport: desktopViewport,
    fullPage: true,
    description: "추천 카테고리와 카테고리 미리보기가 보이는 단계",
  },
  {
    captureId: "onboarding-categories-dropdown-normal",
    route: "/onboarding?scenario=onboarding-categories-dropdown-normal",
    screenTitle: "온보딩 카테고리 추천 드롭다운",
    stateType: "normal",
    outputFile: "screenshots/normal/user/onboarding-categories-dropdown.png",
    viewport: desktopViewport,
    fullPage: true,
    description: "추천 카테고리 드롭다운이 열린 상태",
  },
  {
    captureId: "onboarding-categories-custom-normal",
    route: "/onboarding?scenario=onboarding-categories-custom-normal",
    screenTitle: "온보딩 직접 추가 카테고리 상태",
    stateType: "normal",
    outputFile: "screenshots/normal/user/onboarding-categories-custom.png",
    viewport: desktopViewport,
    fullPage: true,
    description: "직접 추가한 카테고리가 반영된 상태",
  },
  {
    captureId: "onboarding-generating-normal",
    route: "/onboarding?scenario=onboarding-generating-normal",
    screenTitle: "온보딩 템플릿 생성 진행 상태",
    stateType: "normal",
    outputFile: "screenshots/normal/user/onboarding-generating.png",
    viewport: desktopViewport,
    description: "템플릿 자동 생성 진행 중인 상태 화면",
  },
  {
    captureId: "onboarding-complete-normal",
    route: "/onboarding?scenario=onboarding-complete-normal",
    screenTitle: "온보딩 완료 화면",
    stateType: "normal",
    outputFile: "screenshots/normal/user/onboarding-complete.png",
    viewport: desktopViewport,
    description: "온보딩 완료 후 시작 안내가 보이는 화면",
  },
  {
    captureId: "dashboard-normal",
    route: "/app",
    screenTitle: "대시보드 기본 화면",
    stateType: "normal",
    outputFile: "screenshots/normal/user/dashboard.png",
    viewport: desktopViewport,
    description: "메트릭, 최근 메일, 일정 요약이 보이는 대시보드 기본 화면",
  },
  {
    captureId: "inbox-normal",
    route: "/app/inbox",
    screenTitle: "수신함 기본 화면",
    stateType: "normal",
    outputFile: "screenshots/normal/user/inbox.png",
    viewport: desktopViewport,
    description: "메일 목록과 상세, 초안 패널이 함께 보이는 수신함 기본 화면",
  },
  {
    captureId: "inbox-schedule-normal",
    route: "/app/inbox?scenario=inbox-schedule-normal",
    screenTitle: "수신함 일정 감지 화면",
    stateType: "normal",
    outputFile: "screenshots/normal/user/inbox-schedule.png",
    viewport: desktopViewport,
    description: "일정 감지 카드가 함께 보이는 수신함 정상 화면",
  },
  {
    captureId: "inbox-completed-normal",
    route: "/app/inbox?scenario=inbox-completed-normal",
    screenTitle: "수신함 처리 완료 화면",
    stateType: "normal",
    outputFile: "screenshots/normal/user/inbox-completed.png",
    viewport: desktopViewport,
    description: "처리 완료 메일과 발송된 답변 내용이 보이는 정상 화면",
  },
  {
    captureId: "inbox-auto-sent-normal",
    route: "/app/inbox?scenario=inbox-auto-sent-normal",
    screenTitle: "수신함 자동 발송 화면",
    stateType: "normal",
    outputFile: "screenshots/normal/user/inbox-auto-sent.png",
    viewport: desktopViewport,
    description: "자동 발송 메일과 발송된 답변 내용이 보이는 정상 화면",
  },
  {
    captureId: "calendar-normal",
    route: "/app/calendar",
    screenTitle: "캘린더 기본 화면",
    stateType: "normal",
    outputFile: "screenshots/normal/user/calendar.png",
    viewport: desktopViewport,
    description: "월간 캘린더와 일정 상세가 보이는 기본 화면",
  },
  {
    captureId: "calendar-create-normal",
    route: "/app/calendar?scenario=calendar-create-normal",
    screenTitle: "캘린더 일정 추가 다이얼로그",
    stateType: "normal",
    outputFile: "screenshots/normal/user/calendar-create.png",
    viewport: desktopViewport,
    description: "일정 추가 다이얼로그가 열린 정상 상태",
  },
  {
    captureId: "calendar-edit-normal",
    route: "/app/calendar?scenario=calendar-edit-normal",
    screenTitle: "캘린더 일정 수정 다이얼로그",
    stateType: "normal",
    outputFile: "screenshots/normal/user/calendar-edit.png",
    viewport: desktopViewport,
    description: "기존 일정 수정 다이얼로그가 열린 정상 상태",
  },
  {
    captureId: "calendar-delete-normal",
    route: "/app/calendar?scenario=calendar-delete-normal",
    screenTitle: "캘린더 일정 삭제 확인 다이얼로그",
    stateType: "normal",
    outputFile: "screenshots/normal/user/calendar-delete.png",
    viewport: desktopViewport,
    description: "기존 일정 삭제 확인 다이얼로그가 열린 정상 상태",
  },
  {
    captureId: "templates-normal",
    route: "/app/templates",
    screenTitle: "템플릿 라이브러리 기본 화면",
    stateType: "normal",
    outputFile: "screenshots/normal/user/templates.png",
    viewport: desktopViewport,
    description: "템플릿 검색, 목록, 편집 진입이 가능한 기본 화면",
  },
  {
    captureId: "templates-preview-normal",
    route: "/app/templates?scenario=templates-preview-normal",
    screenTitle: "템플릿 미리보기 다이얼로그",
    stateType: "normal",
    outputFile: "screenshots/normal/user/templates-preview.png",
    viewport: desktopViewport,
    description: "템플릿 본문 미리보기 다이얼로그가 열린 정상 상태",
  },
  {
    captureId: "templates-edit-normal",
    route: "/app/templates?scenario=templates-edit-normal",
    screenTitle: "템플릿 편집 다이얼로그",
    stateType: "normal",
    outputFile: "screenshots/normal/user/templates-edit.png",
    viewport: desktopViewport,
    description: "템플릿 수정 다이얼로그가 열린 정상 상태",
  },
  {
    captureId: "templates-create-normal",
    route: "/app/templates?scenario=templates-create-normal",
    screenTitle: "템플릿 생성 다이얼로그",
    stateType: "normal",
    outputFile: "screenshots/normal/user/templates-create.png",
    viewport: desktopViewport,
    description: "새 템플릿 생성 다이얼로그가 열린 정상 상태",
  },
  {
    captureId: "templates-delete-normal",
    route: "/app/templates?scenario=templates-delete-normal",
    screenTitle: "템플릿 삭제 확인 다이얼로그",
    stateType: "normal",
    outputFile: "screenshots/normal/user/templates-delete.png",
    viewport: desktopViewport,
    description: "템플릿 삭제 확인 다이얼로그가 열린 정상 상태",
  },
  {
    captureId: "profile-normal",
    route: "/app/profile",
    screenTitle: "비즈니스 프로필 기본 화면",
    stateType: "normal",
    outputFile: "screenshots/normal/user/profile.png",
    viewport: desktopViewport,
    fullPage: true,
    description: "회사 정보와 자료 업로드, FAQ 설정이 보이는 기본 화면",
  },
  {
    captureId: "profile-faq-dialog-normal",
    route: "/app/profile?scenario=profile-faq-dialog-normal",
    screenTitle: "비즈니스 프로필 FAQ 다이얼로그",
    stateType: "normal",
    outputFile: "screenshots/normal/user/profile-faq-dialog.png",
    viewport: desktopViewport,
    description: "FAQ 항목 추가 다이얼로그가 열린 정상 상태",
  },
  {
    captureId: "profile-faq-delete-normal",
    route: "/app/profile?scenario=profile-faq-delete-normal",
    screenTitle: "비즈니스 프로필 FAQ 삭제 확인 다이얼로그",
    stateType: "normal",
    outputFile: "screenshots/normal/user/profile-faq-delete.png",
    viewport: desktopViewport,
    description: "FAQ 항목 삭제 확인 다이얼로그가 열린 정상 상태",
  },
  {
    captureId: "profile-regenerate-bulk-normal",
    route: "/app/profile?scenario=profile-regenerate-bulk-normal",
    screenTitle: "비즈니스 프로필 일괄 재생성 다이얼로그",
    stateType: "normal",
    outputFile: "screenshots/normal/user/profile-regenerate-bulk.png",
    viewport: desktopViewport,
    description: "영향받는 템플릿 일괄 재생성 다이얼로그가 열린 정상 상태",
  },
  {
    captureId: "profile-regenerate-select-normal",
    route: "/app/profile?scenario=profile-regenerate-select-normal",
    screenTitle: "비즈니스 프로필 재생성 선택 다이얼로그",
    stateType: "normal",
    outputFile: "screenshots/normal/user/profile-regenerate-select.png",
    viewport: desktopViewport,
    description: "재생성할 템플릿을 선택하는 다이얼로그가 열린 정상 상태",
  },
  {
    captureId: "automation-normal",
    route: "/app/automation",
    screenTitle: "자동화 설정 기본 화면",
    stateType: "normal",
    outputFile: "screenshots/normal/user/automation.png",
    viewport: desktopViewport,
    fullPage: true,
    description: "카테고리 규칙과 캘린더 연동 상태를 확인하는 기본 화면",
  },
  {
    captureId: "automation-rule-dialog-normal",
    route: "/app/automation?scenario=automation-rule-dialog-normal",
    screenTitle: "자동화 설정 규칙 추가 다이얼로그",
    stateType: "normal",
    outputFile: "screenshots/normal/user/automation-rule-dialog.png",
    viewport: desktopViewport,
    description: "카테고리 규칙 추가 다이얼로그가 열린 정상 상태",
  },
  {
    captureId: "automation-rule-edit-normal",
    route: "/app/automation?scenario=automation-rule-edit-normal",
    screenTitle: "자동화 설정 규칙 편집 다이얼로그",
    stateType: "normal",
    outputFile: "screenshots/normal/user/automation-rule-edit.png",
    viewport: desktopViewport,
    description: "기존 카테고리 규칙 편집 다이얼로그가 열린 정상 상태",
  },
  {
    captureId: "automation-rule-delete-normal",
    route: "/app/automation?scenario=automation-rule-delete-normal",
    screenTitle: "자동화 설정 규칙 삭제 확인 다이얼로그",
    stateType: "normal",
    outputFile: "screenshots/normal/user/automation-rule-delete.png",
    viewport: desktopViewport,
    description: "카테고리 규칙 삭제 확인 다이얼로그가 열린 정상 상태",
  },
  {
    captureId: "automation-calendar-category-normal",
    route: "/app/automation?scenario=automation-calendar-category-normal",
    screenTitle: "자동화 설정 캘린더 카테고리 다이얼로그",
    stateType: "normal",
    outputFile: "screenshots/normal/user/automation-calendar-category.png",
    viewport: desktopViewport,
    description: "캘린더 자동 등록 카테고리 선택 다이얼로그가 열린 정상 상태",
  },
  {
    captureId: "settings-account-normal",
    route: "/app/settings?tab=account",
    screenTitle: "설정 계정 탭 기본 화면",
    stateType: "normal",
    outputFile: "screenshots/normal/user/settings-account.png",
    viewport: desktopViewport,
    description: "계정 정보와 비밀번호 변경이 보이는 설정 기본 화면",
  },
  {
    captureId: "settings-notifications-normal",
    route: "/app/settings?tab=notifications",
    screenTitle: "설정 알림 탭 기본 화면",
    stateType: "normal",
    outputFile: "screenshots/normal/user/settings-notifications.png",
    viewport: desktopViewport,
    description: "알림 설정 토글이 보이는 설정 기본 화면",
  },
  {
    captureId: "settings-display-normal",
    route: "/app/settings?tab=display",
    screenTitle: "설정 화면 탭 기본 화면",
    stateType: "normal",
    outputFile: "screenshots/normal/user/settings-display.png",
    viewport: desktopViewport,
    description: "테마와 표시 옵션을 조정하는 화면 설정 탭 기본 화면",
  },
  {
    captureId: "settings-email-normal",
    route: "/app/settings?tab=email",
    screenTitle: "설정 이메일 연동 탭 기본 화면",
    stateType: "normal",
    outputFile: "screenshots/normal/user/settings-email.png",
    viewport: desktopViewport,
    description: "연결된 Gmail 계정 목록과 계정 추가 버튼이 보이는 기본 화면",
  },
  {
    captureId: "settings-email-oauth-verify-normal",
    route: "/app/settings?tab=email&scenario=settings-email-oauth-verify-normal",
    screenTitle: "설정 이메일 연동 OAuth 확인 다이얼로그",
    stateType: "normal",
    outputFile: "screenshots/normal/user/settings-email-oauth-verify.png",
    viewport: desktopViewport,
    description: "Google 인증 확인 다이얼로그가 열린 정상 상태",
  },
  {
    captureId: "settings-support-normal",
    route: "/app/settings?tab=support",
    screenTitle: "설정 관리자 문의 탭 기본 화면",
    stateType: "normal",
    outputFile: "screenshots/normal/user/settings-support.png",
    viewport: desktopViewport,
    description: "관리자 문의 작성 폼이 보이는 설정 기본 화면",
  },
  {
    captureId: "settings-support-dialog-normal",
    route: "/app/settings?tab=support&scenario=settings-support-dialog-normal",
    screenTitle: "설정 관리자 문의 작성 다이얼로그",
    stateType: "normal",
    outputFile: "screenshots/normal/user/settings-support-dialog.png",
    viewport: desktopViewport,
    description: "관리자 문의 작성 다이얼로그가 열린 정상 상태",
  },
];

export const adminNormalCaptures = [
  {
    captureId: "admin-dashboard-normal",
    route: "/admin",
    screenTitle: "관리자 대시보드 기본 화면",
    stateType: "normal",
    outputFile: "screenshots/normal/admin/dashboard.png",
    viewport: desktopViewport,
    description: "운영 메트릭과 처리 추이가 보이는 관리자 기본 화면",
  },
  {
    captureId: "admin-users-normal",
    route: "/admin/users",
    screenTitle: "사용자 관리 기본 화면",
    stateType: "normal",
    outputFile: "screenshots/normal/admin/users.png",
    viewport: desktopViewport,
    fullPage: true,
    description: "사용자 목록과 상세 운영 패널이 보이는 관리자 기본 화면",
  },
  {
    captureId: "admin-users-status-dialog-normal",
    route: "/admin/users?scenario=admin-users-status-dialog-normal",
    screenTitle: "사용자 상태 변경 확인 다이얼로그",
    stateType: "normal",
    outputFile: "screenshots/normal/admin/users-status-dialog.png",
    viewport: desktopViewport,
    description: "사용자 활성/비활성 상태 변경 확인 다이얼로그가 열린 화면",
  },
  {
    captureId: "admin-users-google-dialog-normal",
    route: "/admin/users?scenario=admin-users-google-dialog-normal",
    screenTitle: "Google 연동 강제 해제 다이얼로그",
    stateType: "normal",
    outputFile: "screenshots/normal/admin/users-google-dialog.png",
    viewport: desktopViewport,
    description: "Google 연동 강제 해제 확인 다이얼로그가 열린 화면",
  },
  {
    captureId: "admin-template-automation-normal",
    route: "/admin/template-automation",
    screenTitle: "템플릿 자동화 관리 기본 화면",
    stateType: "normal",
    outputFile: "screenshots/normal/admin/template-automation.png",
    viewport: desktopViewport,
    fullPage: true,
    description: "생성 템플릿 통계와 자동화 규칙을 관리하는 기본 화면",
  },
  {
    captureId: "admin-template-automation-rules-normal",
    route: "/admin/template-automation?tab=rules",
    screenTitle: "자동화 규칙 관리 기본 화면",
    stateType: "normal",
    outputFile: "screenshots/normal/admin/template-automation-rules.png",
    viewport: desktopViewport,
    description: "자동화 규칙 목록이 보이는 기본 화면",
  },
  {
    captureId: "admin-template-automation-rule-dialog-normal",
    route: "/admin/template-automation?tab=rules&scenario=admin-template-automation-rule-dialog-normal",
    screenTitle: "자동화 규칙 생성 다이얼로그",
    stateType: "normal",
    outputFile: "screenshots/normal/admin/template-automation-rule-dialog.png",
    viewport: desktopViewport,
    description: "자동화 규칙 생성 다이얼로그가 열린 화면",
  },
  {
    captureId: "admin-template-automation-rule-delete-dialog-normal",
    route: "/admin/template-automation?tab=rules&scenario=admin-template-automation-rule-delete-dialog-normal",
    screenTitle: "자동화 규칙 삭제 다이얼로그",
    stateType: "normal",
    outputFile: "screenshots/normal/admin/template-automation-rule-delete-dialog.png",
    viewport: desktopViewport,
    description: "자동화 규칙 삭제 확인 다이얼로그가 열린 화면",
  },
  {
    captureId: "admin-inquiries-normal",
    route: "/admin/inquiries",
    screenTitle: "문의 대응 기본 화면",
    stateType: "normal",
    outputFile: "screenshots/normal/admin/inquiries.png",
    viewport: desktopViewport,
    fullPage: true,
    description: "문의 목록과 상세 패널이 보이는 관리자 기본 화면",
  },
  {
    captureId: "admin-monitoring-normal",
    route: "/admin/monitoring",
    screenTitle: "시스템 운영 모니터링 기본 화면",
    stateType: "normal",
    outputFile: "screenshots/normal/admin/monitoring.png",
    viewport: desktopViewport,
    fullPage: true,
    description: "실패 또는 대기 상태 작업을 강제 삭제하는 기본 화면",
  },
  {
    captureId: "admin-monitoring-delete-dialog-normal",
    route: "/admin/monitoring?scenario=admin-monitoring-delete-dialog-normal",
    screenTitle: "작업 강제 삭제 다이얼로그",
    stateType: "normal",
    outputFile: "screenshots/normal/admin/monitoring-delete-dialog.png",
    viewport: desktopViewport,
    description: "실패 또는 대기 작업 강제 삭제 확인 다이얼로그가 열린 화면",
  },
];
